# Replace the "â¯" symbol in the prompt with "âœ"
# [character]      # The name of the module we are configuring is "character"
# symbol = "âœ"     # The "symbol" segment is being set to "âœ"

# [aws]
# disabled = true
# style = "bold blue"
# symbol = "ğŸ…° "

# [cmd_duration]
# min_time = 1
# prefix = "underwent "

[git_branch]
symbol = "ğŸŒ± "
truncation_length = "4"
truncation_symbol = ""

[directory]
truncate_to_repo = true
